// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDdU2SJw-RBrfPQSaIpiYRNvOO-iqf89A',
    appId: '1:42096004388:web:e47bcd0389faaa215137b1',
    messagingSenderId: '42096004388',
    projectId: 'fashion-app-ed9d3',
    authDomain: 'fashion-app-ed9d3.firebaseapp.com',
    storageBucket: 'fashion-app-ed9d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoR4Y_HgsEfZ_51JDyePPTLfCFn7BiFoc',
    appId: '1:42096004388:android:32a48eb0dd5a73735137b1',
    messagingSenderId: '42096004388',
    projectId: 'fashion-app-ed9d3',
    storageBucket: 'fashion-app-ed9d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJlgyWMRAo3C4EvfKspOHpZ9U4M0bQ3tM',
    appId: '1:42096004388:ios:28ebed7b0ba3eca65137b1',
    messagingSenderId: '42096004388',
    projectId: 'fashion-app-ed9d3',
    storageBucket: 'fashion-app-ed9d3.firebasestorage.app',
    iosBundleId: 'com.spadini.fashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDdU2SJw-RBrfPQSaIpiYRNvOO-iqf89A',
    appId: '1:42096004388:web:4a5751039046f7f45137b1',
    messagingSenderId: '42096004388',
    projectId: 'fashion-app-ed9d3',
    authDomain: 'fashion-app-ed9d3.firebaseapp.com',
    storageBucket: 'fashion-app-ed9d3.firebasestorage.app',
  );
}
